server:
  port: 80
  #ssl:
    #key-store: tomcat.keystore
    #key-store-type: JKS
    #key-alias: tomcat
    #key-store-password: tomcat
logging:
  level:
    com.lenovo.tripnote.webchat.mapper: DEBUG 
spring:
  profiles: 
    active: pro