server:
  port: 443
  ssl:
    key-store: bjgxly.com.jks
    key-store-type: JKS
    key-store-password: j696g096v465pl
logging:
  level:
    com.lenovo.tripnote.webchat.mapper: DEBUG 
spring:

    resources:
        #设置静态页面路径 可以配置多一个 按照配置顺序依次查询
        static-locations: file:/root/tripnote/static, classpath:/static/
    datasource:
        name: product
        url: jdbc:mysql://172.27.0.8:3306/tripnote_webchat
        username: root
        password: tripnote_lenovo
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  
mybatis:
  mapper-locations: classpath:com/lenovo/tripnote/webchat/mapper/*.xml
  type-aliases-package: com.lenovo.tripnote.webchat.entity
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
   