const SET_LOGIN_SLIDER_INIT = 'SET_LOGIN_SLIDER_INIT'
const SET_ROUTE_INFO = 'SET_ROUTE_INFO'
const SET_ROUTE_LINE_ACTIVE = 'SET_ROUTE_LINE_ACTIVE'
const SET_DAY_SCHEDULE_ACTIVE = 'SET_DAY_SCHEDULE_ACTIVE'
const SET_DAY_INFO = 'SET_DAY_INFO'
const SET_DAY_POI_EDIT_ACTIVE = 'SET_DAY_POI_EDIT_ACTIVE'


export {
    SET_LOGIN_SLIDER_INIT,
    SET_ROUTE_INFO,
    SET_ROUTE_LINE_ACTIVE,
    SET_DAY_SCHEDULE_ACTIVE,
    SET_DAY_INFO,
    SET_DAY_POI_EDIT_ACTIVE,
}
